name: MemorizeTheBlock
version: ${project.version}
main: io.tofpu.memorizetheblock.plugin.MemorizeTheBlockPlugin

authors: [ Tofpu ]
api-version: 1.13
commands:
  memorize:
    description: Memorize the block game!
